force-app/main/default/objects/Case/fields/DX_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>DX_Case_Number__c</fullName>
    <label>Case Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DX_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>DX_Completion_Date__c</fullName>
    <formula>IF(ISPICKVAL(Status,&quot;Resolved&quot;),TODAY(), null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/DX_Site__c.field-meta.xml
<CustomField>
    <fullName>DX_Site__c</fullName>
    <label>Site</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1102 Grand</fullName>
            </value>
            <value>
                <fullName>7801 Nieman Road</fullName>
            </value>
            <value>
                <fullName>210 N Tucker</fullName>
            </value>
            <value>
                <fullName>900 Walnut</fullName>
            </value>
            <value>
                <fullName>1301 Fannin</fullName>
            </value>
            <value>
                <fullName>401 N Broad</fullName>
            </value>
            <value>
                <fullName>717 S Wells</fullName>
            </value>
            <value>
                <fullName>701 W Henry</fullName>
            </value>
            <value>
                <fullName>733 W Henry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DX_viewClosedServiceRequest_ctr.cls
public with sharing class DX_viewClosedServiceRequest_ctr {
    @AuraEnabled(cacheable=true)
    public static List<Case> getClosedServiceRequest() {
        List<Case> lstCase = new List<Case>();
		String IdUser = UserInfo.getUserId();
        String ContactId = getUserInfo(IdUser);
        If(!String.isBlank(ContactId)){
            String AccountId = getContactInfo(ContactId);
            if(!String.isBlank(AccountId)){
            	lstCase = getClosedSR(AccountId);
            }
        }
        return lstCase;
    }
    
    public static String getUserInfo(String UserId){
        List<User> lstUser = [SELECT Id, ContactId FROM User WHERE Id =: UserId Limit 1];
        return lstUser[0].ContactId;
    }
    
    public static String getContactInfo(String ContactId){
        List<Contact> lstContact = [SELECT Id, AccountId FROM Contact WHERE Id =: ContactId Limit 1];
        return lstContact[0].AccountId;
    }
    
    public static List<Case> getClosedSR(String AccountId){
        List<Case> lstCase = [SELECT Id, DX_Case_Number__c, RecordType.Name, Type, Status, DX_Site__c, DX_Completion_Date__c FROM Case WHERE AccountId  =: AccountId AND Status = 'Resolved'];
        return lstCase;
    }
}