force-app/main/default/objects/DX_Access_Managment__c/DX_Access_Managment__c.object-meta.xml
<CustomObject>
    <label>Access Managment</label>
    <nameField>
        <label>Access Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Managment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DX_Access_Managment__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Access Managment</relationshipLabel>
    <relationshipName>Access_Managment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DX_Access_Managment__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Access Managment</relationshipLabel>
    <relationshipName>Access_Managment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DX_Access_Managment__c/fields/Position_Role__c.field-meta.xml
<CustomField>
    <fullName>Position_Role__c</fullName>
    <label>Position/Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DX_viewAccessUserManageInfo_ctr.cls
public class DX_viewAccessUserManageInfo_ctr {
	@AuraEnabled(cacheable=true)
    public static List<DX_Access_Managment__c> getAccessUserManageInfo() {
        List<DX_Access_Managment__c> lstAccessManage = new List<DX_Access_Managment__c>();
        String IdUser = UserInfo.getUserId();
        String ContactId = getUserInfo(IdUser);
        If(!String.isBlank(ContactId)){
            lstAccessManage = getAccessManageInfo(ContactId);
        }
        return lstAccessManage;
    }
    
    public static String getUserInfo(String UserId){
        List<User> lstUser = [SELECT Id, ContactId FROM User WHERE Id =: UserId Limit 1];
        return lstUser[0].ContactId;
    }
    
    public static List<DX_Access_Managment__c> getAccessManageInfo(String ContactId){
        List<DX_Access_Managment__c> lstAccessManage = [SELECT Id, 
                                                               Contact_Name__r.Name,
                                                               Position_Role__c,
                                                               Account_Name__r.Name
                                                        FROM   DX_Access_Managment__c 
                                                        WHERE  Contact_Name__c =: ContactId];
        return lstAccessManage;
    }
}