force-app/main/default/objects/Asset/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Service_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Service_Order_Line_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related Service Order</description>
    <label>Service Order Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Asset.recordType-meta.xml
<RecordType>
    <fullName>Asset</fullName>
    <active>true</active>
    <label>Asset</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Cage.recordType-meta.xml
<RecordType>
    <fullName>Cage</fullName>
    <active>true</active>
    <description>Private Cage in a data hall.</description>
    <label>Cage</label>
</RecordType>

force-app/main/default/objects/DC_Cage__c/DC_Cage__c.object-meta.xml
<CustomObject>
    <label>Cage</label>
    <nameField>
        <label>Cage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Cage__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Ten character short name of the Cage used to support naming convention.</description>
    <label>Short Name</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Cage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Cage</fullName>
            </value>
            <value>
                <fullName>Virtual Cage</fullName>
            </value>
            <value>
                <fullName>Pod</fullName>
            </value>
            <value>
                <fullName>Private Suite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Data_Hall__c/DC_Data_Hall__c.object-meta.xml
<CustomObject>
    <label>Data Hall</label>
    <nameField>
        <label>Data Hall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Halls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Data_Hall__c/fields/DC_Floor__c.field-meta.xml
<CustomField>
    <fullName>DC_Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DC Floor</label>
    <referenceTo>DC_Floor__c</referenceTo>
    <relationshipLabel>Data Halls</relationshipLabel>
    <relationshipName>Data_Halls</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Data_Hall__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Floor</label>
    <referenceTo>DC_Floor__c</referenceTo>
    <relationshipLabel>Data Halls</relationshipLabel>
    <relationshipName>Data_Halls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Data_Hall__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Four character short name of the data hall used to support naming convention.</description>
    <label>Short Name</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DC_Floor__c/DC_Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Floor__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Floor__c/fields/Floor_number__c.field-meta.xml
<CustomField>
    <fullName>Floor_number__c</fullName>
    <description>The numerical level of the floor - decimal reserved for Mezzanine spaces.</description>
    <label>Floor_Number</label>
    <precision>3</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Floor__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Two character short name of the floor used to support naming convention.</description>
    <label>Short Name</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Meet_Me_Room__c/DC_Meet_Me_Room__c.object-meta.xml
<CustomObject>
    <label>Meet Me Room</label>
    <nameField>
        <label>Meet Me Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meet Me Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Meet_Me_Room__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Two character short name of the MMR used to support naming convention.</description>
    <label>Short Name</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Panel__c/DC_Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <label>Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Panel__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Two character short name of the Panel used to support naming convention.</description>
    <label>Short Name</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Port__c/DC_Port__c.object-meta.xml
<CustomObject>
    <label>Port</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Port__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Ten character short name of the Port used to support naming convention. Dependent on Mod during automatic creation.</description>
    <label>Short Name</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Rack__c/DC_Rack__c.object-meta.xml
<CustomObject>
    <label>Rack</label>
    <nameField>
        <label>Rack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Rack__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Two character short name of the Rack used to support naming convention.</description>
    <label>Short Name</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Tenant_Suite__c/DC_Tenant_Suite__c.object-meta.xml
<CustomObject>
    <label>Tenant Suite</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tenant Suites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Tenant_Suite__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The floor that this Tenant Suite is located on.</description>
    <label>Floor</label>
    <referenceTo>DC_Floor__c</referenceTo>
    <relationshipLabel>Tenant Suites</relationshipLabel>
    <relationshipName>Tenant_Suites</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Tenant_Suite__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Four character short name of the Tenant Suite used to support naming convention.</description>
    <label>Short Name</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DC_Allocation_Required__c.field-meta.xml
<CustomField>
    <fullName>DC_Allocation_Required__c</fullName>
    <label>Allocation Required</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DC_Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>DC_Asset_Type__c</fullName>
    <label>Asset Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DC_Income_Category__c.field-meta.xml
<CustomField>
    <fullName>DC_Income_Category__c</fullName>
    <label>Income Category</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DC_Number_of_Assets__c.field-meta.xml
<CustomField>
    <fullName>DC_Number_of_Assets__c</fullName>
    <label>Number of Assets</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>High level product segmentation.</description>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Space</fullName>
            </value>
            <value>
                <fullName>Power</fullName>
            </value>
            <value>
                <fullName>Connectivity</fullName>
            </value>
            <value>
                <fullName>IP</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>IPS</fullName>
            </value>
            <value>
                <fullName>IDF</fullName>
            </value>
            <value>
                <fullName>CDT</fullName>
            </value>
            <value>
                <fullName>TSL</fullName>
            </value>
            <value>
                <fullName>H12</fullName>
            </value>
            <value>
                <fullName>PCA</fullName>
            </value>
            <value>
                <fullName>PCB</fullName>
            </value>
            <value>
                <fullName>H144</fullName>
            </value>
            <value>
                <fullName>RUS</fullName>
            </value>
            <value>
                <fullName>POE</fullName>
            </value>
            <value>
                <fullName>H21</fullName>
            </value>
            <value>
                <fullName>H24</fullName>
            </value>
            <value>
                <fullName>H28</fullName>
            </value>
            <value>
                <fullName>CAB</fullName>
            </value>
            <value>
                <fullName>H48</fullName>
            </value>
            <value>
                <fullName>H06</fullName>
            </value>
            <value>
                <fullName>H72</fullName>
            </value>
            <value>
                <fullName>H96</fullName>
            </value>
            <value>
                <fullName>BPC</fullName>
            </value>
            <value>
                <fullName>ANT</fullName>
            </value>
            <value>
                <fullName>MBX</fullName>
            </value>
            <value>
                <fullName>OBS</fullName>
            </value>
            <value>
                <fullName>CGE</fullName>
            </value>
            <value>
                <fullName>XO</fullName>
            </value>
            <value>
                <fullName>HRC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DC_Allocation_Required__c.field-meta.xml
<CustomField>
    <fullName>DC_Allocation_Required__c</fullName>
    <formula>Product2.DC_Allocation_Required__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Allocation Required</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DC_Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>DC_Asset_Type__c</fullName>
    <formula>Product2.DC_Asset_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asset Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DC_Income_Category__c.field-meta.xml
<CustomField>
    <fullName>DC_Income_Category__c</fullName>
    <formula>Product2.DC_Income_Category__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Income Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DC_Number_of_Assets__c.field-meta.xml
<CustomField>
    <fullName>DC_Number_of_Assets__c</fullName>
    <formula>Product2.DC_Number_of_Assets__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Assets</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DX_ConnectPorts_tst.cls
@IsTest
public class DX_ConnectPorts_tst {

    @testSetup
    static void setup() {
        
        Account Account = new Account(Name = 'Test Account');
        insert Account;
        
        // Create a new Product record
        Product2 product = new Product2(Name = 'Test Product', ProductCode = 'TP01', Description = 'Test Product Description', IsActive = true, Product_Group__c = 'ExampleProductGroup', Product_Category__c = 'Power', DC_Allocation_Required__c = 'Yes', DC_Asset_Type__c = 'Fiber Pair', DC_Income_Category__c = 'test', DC_Number_of_Assets__c = '1');
        // Insert the Product record
        insert product;

        // Create a new PricebookEntry record
        PricebookEntry pricebookEntry = new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(), Product2Id = product.Id, UnitPrice = 100, IsActive = true);
        // Insert the PricebookEntry record
        insert pricebookEntry;
        
        // Create a new Pricebook2 record
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        
        // Create a price book entry with a custom price.
        PricebookEntry customPrice = new PricebookEntry(Pricebook2Id = customPB.Id, Product2Id = product.Id, UnitPrice = 12000, IsActive = true);
        insert customPrice;

        Opportunity Opportunity = new Opportunity(Name = 'Nombre de la  oportunidad de prueba', StageName = 'Qualifying', CloseDate = Date.today().addDays(30), Amount = 10000, Probability = 50, LeadSource = 'Web', Type = 'New Logo', AccountId = Account.Id); 
        // Insert the Opportunity record
        insert Opportunity;

        // Create a new Order record
        Quote Service_order = new Quote(Name = 'Test Order', Status = 'Draft', Pricebook2Id = customPB.Id, OpportunityId = Opportunity.Id, Commencement_Date__c = Date.today(), Term__c = 'test');
        // Insert the Order record
        insert Service_order;

        // Create a new OrderItem record
        QuoteLineItem ServiceOrderLineItem = new QuoteLineItem(QuoteId = Service_order.Id, PricebookEntryId = customPrice.Id, Quantity = 1, UnitPrice = pricebookEntry.UnitPrice);
        // Insert the Service Order Line Item record
        insert ServiceOrderLineItem;

        // Create a new Asset record
        Asset asset = new Asset(Name = 'Test Asset', AccountId = Account.Id, SerialNumber = '123456', InstallDate = Date.today(), UsageEndDate = Date.today().addYears(1), Status = 'Purchased', Service_Order_Line_Item__c = ServiceOrderLineItem.Id, Opportunity__c = Opportunity.Id);
        // Insert the Asset record
        insert asset;
        
        // Create a new Building__c record
        Building__c building = new Building__c(Name = 'Test Building');
        insert building;
        
        // Create a new DC_Floor__c record
        DC_Floor__c Floor = new DC_Floor__c(Name = 'Test Floor', Building__c = building.Id , Floor_Number__c = 1, Short_Name__c = 'FL', Total_Square_Feet__c = 4);
        insert Floor;
        
        // Insert a test Data Hall
        DC_Data_Hall__c dataHall = new DC_Data_Hall__c(Name = 'Test Data Hall', DC_Floor__c = Floor.Id, Short_Name__c = 'test');
        insert dataHall;
        
        // Insert a test Cage
        DC_Cage__c cage = new DC_Cage__c(Name = 'Test Cage', Data_Hall__c = dataHall.Id, Type__c = 'Pod', MRI_Suite_ID__c = '34', Short_Name__c = 'CE');
        insert cage;
        
        // Create a test Tenant Suite record associated with the test Building
        DC_Tenant_Suite__c TenantSuite = new DC_Tenant_Suite__c(Name = 'Test Tenant Suite', Floor__c = Floor.Id, Status__c = 'Occupied', Suite_Use__c = 'Powered Shell', Account__c = Account.Id, Square_Footage__c = 2, Short_Name__c = 'TT');
        insert TenantSuite;
        
        DC_Meet_Me_Room__c MeetMeRoom = new DC_Meet_Me_Room__c(Name = 'Room 101', Data_Hall__c = dataHall.Id, Short_Name__c = 'MMR');
        insert MeetMeRoom;
        
        DC_Rack__c Rack = new DC_Rack__c(Name = 'Rack 1', Meet_Me_Room__c = MeetMeRoom.Id, MRI_Suite_ID__c = '435', Number_of_Rack_Units__c =2, Row_Number__c = 2, Short_Name__c = 'RK');
        insert Rack;
        
        DC_Panel__c Panel = new DC_Panel__c(Rack__c = Rack.Id, Mod_Model__c = 'Yes', Height_RU__c = 2, MRI_Suite_ID__c = '435', Short_Name__c = 'Pl', Starting_Position_RU__c = 1, Asset__c = asset.Id);
		insert Panel;
        
        DC_Port__c Port = new DC_Port__c(Name = 'Port', Panel__c = Panel.Id, Short_Name__c = 'PT', Port_Status__c = 'No Homerun');
		insert Port;
    }
    
    @IsTest
    static void getPanel() {
        
        DC_Panel__c panel = [SELECT Id FROM DC_Panel__c LIMIT 1];
        
        DC_Port__c Port = [SELECT Id FROM DC_Port__c LIMIT 1];

        // Call the method being tested with the ID of the Panel record
        List<DX_DCIM_DataAccess.wrapperResult> result = DX_ConnectPorts_ctr.getPorts(panel.Id);

        // Assert that the method returns the expected Port record
        System.assertEquals(1, result.size());
        System.assertEquals(Port.Id, result[0].value);
    }
    
}