force-app/main/default/objects/Asset/fields/Service_Order__c.field-meta.xml
<CustomField>
    <fullName>Service_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Order</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Asset.recordType-meta.xml
<RecordType>
    <fullName>Asset</fullName>
    <active>true</active>
    <label>Asset</label>
</RecordType>

force-app/main/default/objects/Case/fields/DX_Service_Order__c.field-meta.xml
<CustomField>
    <fullName>DX_Service_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Order</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Panel__c/DC_Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <label>Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Panel__c/fields/Height_RU__c.field-meta.xml
<CustomField>
    <fullName>Height_RU__c</fullName>
    <description>Height of this Panel in RU</description>
    <label>Height (RU)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Panel__c/fields/Rack__c.field-meta.xml
<CustomField>
    <fullName>Rack__c</fullName>
    <label>Rack</label>
    <referenceTo>DC_Rack__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DC_Panel__c/fields/Service_Order__c.field-meta.xml
<CustomField>
    <fullName>Service_Order__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; &amp;   Asset__r.Service_Order__r.Id ,  Asset__r.Service_Order__r.QuoteNumber  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Panel__c/fields/Starting_Position_RU__c.field-meta.xml
<CustomField>
    <fullName>Starting_Position_RU__c</fullName>
    <description>Starting Position of this Panel in the Rack. 1 is the bottom RU.</description>
    <label>Starting Position (RU)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Rack__c/DC_Rack__c.object-meta.xml
<CustomObject>
    <label>Rack</label>
    <nameField>
        <label>Rack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Rack__c/fields/Number_of_Rack_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Rack_Units__c</fullName>
    <description>Height of this rack in Rack Units</description>
    <label>Number of Rack Units</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Rack__c/fields/Rack_Row__c.field-meta.xml
<CustomField>
    <fullName>Rack_Row__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rack Row</label>
    <referenceTo>DC_Rack_Row__c</referenceTo>
    <relationshipLabel>Racks</relationshipLabel>
    <relationshipName>Racks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Rack__c/fields/Service_Order__c.field-meta.xml
<CustomField>
    <fullName>Service_Order__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; &amp;  Asset__r.Service_Order__r.Id, Asset__r.Service_Order__r.Service_Order_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Rack_Row__c/DC_Rack_Row__c.object-meta.xml
<CustomObject>
    <label>Rack Row</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rack Rows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseRelatedAssetSelectionControllerTest.cls
@isTest
public class CaseRelatedAssetSelectionControllerTest {
    @testSetup
    static void setupTestData() {
        //     RecordType
        //     Account metaAccount = [SELECT Id FROM Account WHERE Name = 'Meta' LIMIT 1];
        //     System.debug('metaAccount: ' + metaAccount);
        //     // Create test Opportunity
        //     Opportunity testOpp = [SELECT Id FROM Opportunity WHERE AccountId = :metaAccount.Id LIMIT 1];
        //     System.debug('testOpp: ' + testOpp);
        
        //     Quote testQuote = new Quote(Name = 'Test Quote', OpportunityId = testOpp.Id, Commencement_Date__c = Date.today().addDays(30), Term__c = String.valueOf(12));
        //     insert testQuote;
        //     System.debug('testQuote: ' + testQuote);
        
        //     // Create test Case
        //     Case testCase = new Case(Subject = 'Test Case', DX_Service_Order__c = testQuote.Id);
        //     insert testCase;
        //     System.debug('testCase: ' + testCase);
        
        //     // Create test Assets
        //     Asset testAsset = new Asset(Name = 'Test Asset', Service_Order__c = testCase.DX_Service_Order__c);
        //     insert testAsset;
        //     System.debug('testAsset: ' + testAsset);
        //     // Create test DC_Rack__c
        //     DC_Rack__c testRack = new DC_Rack__c(Name = 'Test Rack', Rack_Row__c = 'TestRackRow', Number_of_Rack_Units__c = 42);
        //     insert testRack;
        //     System.debug('testRack: ' + testRack);
        //     // Create test DC_Panel__c
        //     DC_Panel__c testPanel = new DC_Panel__c(Name = 'Test Panel', Rack__c = testRack.Id, Height_RU__c = 2, Starting_Position_RU__c = 1);
        //     insert testPanel;
        //     System.debug('testPanel: ' + testPanel);
        //     // Create test RDraw__Interaction_Definition__c
        RDraw__Interaction_Definition__c testInteractionDef = new RDraw__Interaction_Definition__c(RDraw__Name__c = 'Test Interaction Definition', RDraw__Type__c = '2D_Scene_Settings', RDraw__Associated_Object__c = 'DC_Rack_Row__c', RDraw__Settings__c = '{}');
        insert testInteractionDef;
        System.debug('testInteractionDef: ' + testInteractionDef);
    }
    
    @isTest
    static void testGetRelatedAssets() {
        // Test with a Case having DX_Service_Order__c
        Test.startTest();
        Map<String, Object> result = CaseRelatedAssetSelectionController.getRelatedAssets('XXXXXXXXXXXXXXXXXX');
        Test.stopTest();
        System.assertNotEquals(null, result);
        // System.assertEquals('Test Case', result.get('caseName'));
        // System.assertNotEquals(null, result.get('assets'));
    }
    
    @isTest
    static void testGetCanvasSceneForRackRow() {
        // Test with valid rackRowId and desiredUSize
        Test.startTest();
        RDraw.CanvasScene scene = CaseRelatedAssetSelectionController.getCanvasSceneForRackRow('TestRackRow', 1);
        Test.stopTest();
        System.assertNotEquals(null, scene);
    }
    
    @isTest
    static void testGetRackRowTemplateInteractionDefinition() {
        // Test the retrieval of the interaction definition
        Test.startTest();
        RDraw__Interaction_Definition__c interactionDef = CaseRelatedAssetSelectionController.getRackRowTemplateInteractionDefinition();
        Test.stopTest();
        System.assertNotEquals(null, interactionDef);
    }
}