force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Cross_Connect__c/DC_Cross_Connect__c.object-meta.xml
<CustomObject>
    <label>Cross Connect</label>
    <nameField>
        <label>Cross Connect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross Connects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Cross_Connect__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Get Building Name from a formula for reference to the Customer through the customer portal.</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Cross Connects</relationshipLabel>
    <relationshipName>Cross_Connects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Cross_Connect__c/fields/Destination_Account__c.field-meta.xml
<CustomField>
    <fullName>Destination_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Account that the requesting party of the Cross Connect is seeking to connect to.</description>
    <label>Destination Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cross Connects (Destination Account)</relationshipLabel>
    <relationshipName>Cross_Connects1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Cross_Connect__c/fields/Origination_Account__c.field-meta.xml
<CustomField>
    <fullName>Origination_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Account that is requesting this Cross Connect.</description>
    <label>Origination Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cross Connects</relationshipLabel>
    <relationshipName>Cross_Connects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Cross_Connect__c/fields/Xconnect_Status__c.field-meta.xml
<CustomField>
    <fullName>Xconnect_Status__c</fullName>
    <description>Determines the status of the Cross Connect. Active means actively connected, disconnected means it is no longer in place, and in progress is the plaseholder status for any Cases in progress.</description>
    <label>Xconnect Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Connected</fullName>
            </value>
            <value>
                <fullName>Disconnected</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DX_viewCrossConnectsInformation_ctr.cls
/**
 * @Description       : 
 * @Author            : cristianivan.ruiz@salesforce.com
 * @Code Coverage     : 
 * @last modified on  : 11-01-2024
 * @last modified by  : cristianivan.ruiz@salesforce.com
**/
public class DX_viewCrossConnectsInformation_ctr {
    @AuraEnabled(cacheable=true)
    public static List<DC_Cross_Connect__c> getCrossConnets() {
        List<DC_Cross_Connect__c> lstCrossConnect = new List<DC_Cross_Connect__c>();
        String IdUser = UserInfo.getUserId();
        String ContactId = getUserInfo(IdUser);
        If(!String.isBlank(ContactId)){
            String AccountId = getContactInfo(ContactId);
            if(!String.isBlank(AccountId)){
                lstCrossConnect = getCrossConnectInfo(AccountId);
            }
        }
        return lstCrossConnect;
    }
    
    public static String getUserInfo(String UserId){
        List<User> lstUser = [SELECT Id, ContactId FROM User WHERE Id =: UserId Limit 1];
        return lstUser[0].ContactId;
    }
    
    public static String getContactInfo(String ContactId){
        List<Contact> lstContact = [SELECT Id, AccountId FROM Contact WHERE Id =: ContactId Limit 1];
        return lstContact[0].AccountId;
    }
    
    public static List<DC_Cross_Connect__c> getCrossConnectInfo(String AccountId){
        List<DC_Cross_Connect__c> lstCrossConnect = [SELECT Id, 
                                                            Name,
                                                            Building__r.Name,
                                                            Origination_Account__r.Name,
                                                            Destination_Account__r.Name,
                                                            Xconnect_Status__c  
                                                     FROM 	DC_Cross_Connect__c 
                                                     WHERE 	Origination_Account__c =: AccountId
                                                     OR		Destination_Account__c =: AccountId];
        return lstCrossConnect;
    }
}