force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Cabinet__c/DC_Cabinet__c.object-meta.xml
<CustomObject>
    <label>Cabinet</label>
    <nameField>
        <label>Cabinet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cabinets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Cabinet__c/fields/Cabinet_Equivalent__c.field-meta.xml
<CustomField>
    <fullName>Cabinet_Equivalent__c</fullName>
    <description>Determines the number of cabinets this represents (1.0,0.5,0.33)</description>
    <label>Cabinet Equivalent</label>
    <precision>3</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Cabinet__c/fields/Cage__c.field-meta.xml
<CustomField>
    <fullName>Cage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Cage this Cabinet is in.</description>
    <label>Cage</label>
    <referenceTo>DC_Cage__c</referenceTo>
    <relationshipLabel>Cabinets</relationshipLabel>
    <relationshipName>Cabinets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Cabinet__c/fields/Data_Hall__c.field-meta.xml
<CustomField>
    <fullName>Data_Hall__c</fullName>
    <formula>HYPERLINK(&apos;/&apos; &amp; Cage__r.Data_Hall__r.Id , Cage__r.Data_Hall__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data Hall</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Cabinet__c/fields/Depth_in__c.field-meta.xml
<CustomField>
    <fullName>Depth_in__c</fullName>
    <description>The depth of the cabinet in inches.</description>
    <label>Depth (in)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Cabinet__c/fields/Height_RU__c.field-meta.xml
<CustomField>
    <fullName>Height_RU__c</fullName>
    <description>The height of the cabinet in RU.</description>
    <label>Height (RU)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Cabinet__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Ten character short name of the Cabinet used to support naming convention.</description>
    <label>Short Name</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Cabinet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>ROFR</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Cabinet__c/fields/Width_in__c.field-meta.xml
<CustomField>
    <fullName>Width_in__c</fullName>
    <description>The width of the cabinet in inches.</description>
    <label>Width (in)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Cage__c/DC_Cage__c.object-meta.xml
<CustomObject>
    <label>Cage</label>
    <nameField>
        <label>Cage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Cage__c/fields/Data_Hall__c.field-meta.xml
<CustomField>
    <fullName>Data_Hall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Data Hall this Cage is in.</description>
    <label>Data Hall</label>
    <referenceTo>DC_Data_Hall__c</referenceTo>
    <relationshipLabel>Cages</relationshipLabel>
    <relationshipName>Cages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Cage__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Ten character short name of the Cage used to support naming convention.</description>
    <label>Short Name</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Cage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>ROFR</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Netrality Virtual Cage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Cage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Cage</fullName>
            </value>
            <value>
                <fullName>Virtual Cage</fullName>
            </value>
            <value>
                <fullName>Pod</fullName>
            </value>
            <value>
                <fullName>Private Suite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Data_Hall__c/DC_Data_Hall__c.object-meta.xml
<CustomObject>
    <label>Data Hall</label>
    <nameField>
        <label>Data Hall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Halls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Data_Hall__c/fields/DC_Floor__c.field-meta.xml
<CustomField>
    <fullName>DC_Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DC Floor</label>
    <referenceTo>DC_Floor__c</referenceTo>
    <relationshipLabel>Data Halls</relationshipLabel>
    <relationshipName>Data_Halls</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Data_Hall__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Four character short name of the data hall used to support naming convention.</description>
    <label>Short Name</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DC_Floor__c/DC_Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Floor__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Floor__c/fields/Floor_number__c.field-meta.xml
<CustomField>
    <fullName>Floor_number__c</fullName>
    <description>The numerical level of the floor - decimal reserved for Mezzanine spaces.</description>
    <label>Floor_Number</label>
    <precision>3</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Floor__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Two character short name of the floor used to support naming convention.</description>
    <label>Short Name</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Floor__c/fields/Total_Square_Feet__c.field-meta.xml
<CustomField>
    <fullName>Total_Square_Feet__c</fullName>
    <description>Total square footage of this floor</description>
    <label>Total Square Feet</label>
    <precision>7</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DX_PanelSelectorCabinets_tst.cls
/**
 * @Description       : 
 * @Author            : cristianivan.ruiz@salesforce.com
 * @Code Coverage     : 
 * @last modified on  : 12-18-2024
 * @last modified by  : cristianivan.ruiz@salesforce.com
**/
@IsTest
public class DX_PanelSelectorCabinets_tst {
    @testSetup
    static void setup() {

        // Create a new Building__c record
        Building__c building = new Building__c(Name = 'Test Building');
        insert building;

        // Create a new DC_Floor__c record
        DC_Floor__c Floor = new DC_Floor__c(Name = 'Test Floor', Building__c = building.Id , Floor_Number__c = 1, Short_Name__c = 'FL', Total_Square_Feet__c = 4);
        insert Floor;

        // Insert a test Data Hall
        DC_Data_Hall__c dataHall = new DC_Data_Hall__c(Name = 'Test Data Hall', DC_Floor__c = Floor.Id, Short_Name__c = 'test');
        insert dataHall;
        
        // Insert a test Cage
        DC_Cage__c cage = new DC_Cage__c(Name = 'Test Cage', Data_Hall__c = dataHall.Id, Type__c = 'Pod', MRI_Suite_ID__c = '34', Short_Name__c = 'CE');
        insert cage;
        
        // Insert a test Cabinet
        DC_Cabinet__c cabinet = new DC_Cabinet__c(Name = 'Test Cabinet', Cage__c =  cage.Id, Status__c = 'Occupied', Cabinet_Equivalent__c = 2, Depth_in__c = 2, Height_RU__c = 1, MRI_Suite_ID__c = '245', Short_Name__c = 'CT', Width_in__c = 3);
        insert cabinet;
    }

    @IsTest
    static void testGetFloor() {
        Building__c building = [SELECT Id FROM Building__c LIMIT 1];
        
        Test.startTest();
        List<DX_DCIM_DataAccess.wrapperResult> lstwrapperResult = DX_PanelSelectorCabinets_ctr.getFloors(building.Id);
        Test.stopTest();
        
        System.assertEquals(1, lstwrapperResult.size());
    }

    @IsTest
    static void testGetDataHall() {
        DC_Floor__c Floor = [SELECT Id FROM DC_Floor__c LIMIT 1];
        
        Test.startTest();
        List<DX_DCIM_DataAccess.wrapperResult> lstwrapperResult = DX_PanelSelectorCabinets_ctr.getDataHalls(Floor.Id);
        Test.stopTest();
        
        System.assertEquals(1, lstwrapperResult.size());
    }
    
    @IsTest
    static void testGetCages() {
        DC_Data_Hall__c dataHall = [SELECT Id FROM DC_Data_Hall__c LIMIT 1];
        
        Test.startTest();
        List<DX_DCIM_DataAccess.wrapperResult> lstwrapperResult = DX_PanelSelectorCabinets_ctr.getCages(dataHall.Id);
        Test.stopTest();
        
        System.assertEquals(1, lstwrapperResult.size());
    }
    
    @IsTest
    static void testGetCabinets() {
        DC_Cage__c cage = [SELECT Id FROM DC_Cage__c LIMIT 1];
        
        Test.startTest();
        List<DX_DCIM_DataAccess.wrapperResult> lstwrapperResult = DX_PanelSelectorCabinets_ctr.getCabinets(cage.Id);
        Test.stopTest();
        
        System.assertEquals(1, lstwrapperResult.size());
    }
}