force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Data_Hall__c/DC_Data_Hall__c.object-meta.xml
<CustomObject>
    <label>Data Hall</label>
    <nameField>
        <label>Data Hall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Halls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Data_Hall__c/fields/DC_Floor__c.field-meta.xml
<CustomField>
    <fullName>DC_Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DC Floor</label>
    <referenceTo>DC_Floor__c</referenceTo>
    <relationshipLabel>Data Halls</relationshipLabel>
    <relationshipName>Data_Halls</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Data_Hall__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Four character short name of the data hall used to support naming convention.</description>
    <label>Short Name</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DC_Floor__c/DC_Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Floor__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Floor__c/fields/Floor_number__c.field-meta.xml
<CustomField>
    <fullName>Floor_number__c</fullName>
    <description>The numerical level of the floor - decimal reserved for Mezzanine spaces.</description>
    <label>Floor_Number</label>
    <precision>3</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Floor__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Two character short name of the floor used to support naming convention.</description>
    <label>Short Name</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Floor__c/fields/Total_Square_Feet__c.field-meta.xml
<CustomField>
    <fullName>Total_Square_Feet__c</fullName>
    <description>Total square footage of this floor</description>
    <label>Total Square Feet</label>
    <precision>7</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Meet_Me_Room__c/DC_Meet_Me_Room__c.object-meta.xml
<CustomObject>
    <label>Meet Me Room</label>
    <nameField>
        <label>Meet Me Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meet Me Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Meet_Me_Room__c/fields/Data_Hall__c.field-meta.xml
<CustomField>
    <fullName>Data_Hall__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Data Hall</label>
    <referenceTo>DC_Data_Hall__c</referenceTo>
    <relationshipLabel>Meet Me Rooms</relationshipLabel>
    <relationshipName>Meet_Me_Rooms</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Meet_Me_Room__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Two character short name of the MMR used to support naming convention.</description>
    <label>Short Name</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Rack__c/DC_Rack__c.object-meta.xml
<CustomObject>
    <label>Rack</label>
    <nameField>
        <label>Rack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Rack__c/fields/Meet_Me_Room__c.field-meta.xml
<CustomField>
    <fullName>Meet_Me_Room__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Meet Me Room</label>
    <referenceTo>DC_Meet_Me_Room__c</referenceTo>
    <relationshipLabel>Racks</relationshipLabel>
    <relationshipName>Racks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Rack__c/fields/MRI_Suite_ID__c.field-meta.xml
<CustomField>
    <fullName>MRI_Suite_ID__c</fullName>
    <label>MRI Suite ID</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Rack__c/fields/Number_of_Rack_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Rack_Units__c</fullName>
    <description>Height of this rack in Rack Units</description>
    <label>Number of Rack Units</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Rack__c/fields/Row_Number__c.field-meta.xml
<CustomField>
    <fullName>Row_Number__c</fullName>
    <description>The Row in the Meet Me Room that this Rack Occupies, for grouping Racks together</description>
    <label>Row Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Rack__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Two character short name of the Rack used to support naming convention.</description>
    <label>Short Name</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DX_PanelSelectorRacks_tst.cls
/**
 * @Description       : 
 * @Author            : cristianivan.ruiz@salesforce.com
 * @Code Coverage     : 
 * @last modified on  : 12-18-2024
 * @last modified by  : cristianivan.ruiz@salesforce.com
**/
@IsTest
public with sharing class DX_PanelSelectorRacks_tst {
    @testSetup
    static void setup() {

        // Create a new Building__c record
        Building__c building = new Building__c(Name = 'Test Building');
        insert building;

        // Create a new DC_Floor__c record
        DC_Floor__c Floor = new DC_Floor__c(Name = 'Test Floor', Building__c = building.Id , Floor_Number__c = 1, Short_Name__c = 'FL', Total_Square_Feet__c = 4);
        insert Floor;

        // Insert a test Data Hall
        DC_Data_Hall__c DataHall = new DC_Data_Hall__c(Name = 'Test Data Hall', DC_Floor__c = Floor.Id, Short_Name__c = 'test');
        insert DataHall;
        
        DC_Meet_Me_Room__c MeetMeRoom = new DC_Meet_Me_Room__c(Name = 'Room 101', Data_Hall__c = DataHall.Id, Short_Name__c = 'MMR');
        insert MeetMeRoom;
        
        DC_Rack__c Rack = new DC_Rack__c(Name = 'Rack 1', Meet_Me_Room__c = MeetMeRoom.Id, MRI_Suite_ID__c = '435', Number_of_Rack_Units__c =2, Row_Number__c = 2, Short_Name__c = 'RK');
        insert Rack;
    }

    @IsTest
    static void testGetFloor() {
        Building__c building = [SELECT Id FROM Building__c LIMIT 1];
        
        Test.startTest();
        List<DX_DCIM_DataAccess.wrapperResult> lstwrapperResult = DX_PanelSelectorRacks_ctr.getFloors(building.Id);
        Test.stopTest();
        
        System.assertEquals(1, lstwrapperResult.size());
    }

    @IsTest
    static void testGetDataHall() {
        DC_Floor__c Floor = [SELECT Id FROM DC_Floor__c LIMIT 1];
        
        Test.startTest();
        List<DX_DCIM_DataAccess.wrapperResult> lstwrapperResult = DX_PanelSelectorRacks_ctr.getDataHalls(Floor.Id);
        Test.stopTest();
        
        System.assertEquals(1, lstwrapperResult.size());
    }
    
    @IsTest
    static void testGetMeetMeRooms() {
        DC_Data_Hall__c DataHall = [SELECT Id FROM DC_Data_Hall__c LIMIT 1];
        
        Test.startTest();
        List<DX_DCIM_DataAccess.wrapperResult> lstwrapperResult = DX_PanelSelectorRacks_ctr.getMeetMeRooms(DataHall.Id);
        Test.stopTest();
        
        System.assertEquals(1, lstwrapperResult.size());
    }

    @IsTest
    static void testGetRacks() {
        DC_Meet_Me_Room__c MeetMeRoom = [SELECT Id FROM DC_Meet_Me_Room__c LIMIT 1];
        
        Test.startTest();
        List<DX_DCIM_DataAccess.wrapperResult> lstwrapperResult = DX_PanelSelectorRacks_ctr.getRacks(MeetMeRoom.Id);
        Test.stopTest();
        
        System.assertEquals(1, lstwrapperResult.size());
    }
    
}