force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Cross_Connect__c/DC_Cross_Connect__c.object-meta.xml
<CustomObject>
    <label>Cross Connect</label>
    <nameField>
        <label>Cross Connect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross Connects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Cross_Connect__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Get Building Name from a formula for reference to the Customer through the customer portal.</description>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Cross Connects</relationshipLabel>
    <relationshipName>Cross_Connects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Cross_Connect__c/fields/Destination_Account__c.field-meta.xml
<CustomField>
    <fullName>Destination_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Account that the requesting party of the Cross Connect is seeking to connect to.</description>
    <label>Destination Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cross Connects (Destination Account)</relationshipLabel>
    <relationshipName>Cross_Connects1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Cross_Connect__c/fields/Destination_Port__c.field-meta.xml
<CustomField>
    <fullName>Destination_Port__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Port of the Account that the requesting party of the Cross Connect is seeking to connect to.</description>
    <label>Destination Port</label>
    <referenceTo>DC_Port__c</referenceTo>
    <relationshipLabel>Cross Connects (Destination Port)</relationshipLabel>
    <relationshipName>Cross_Connects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Cross_Connect__c/fields/Origination_Account__c.field-meta.xml
<CustomField>
    <fullName>Origination_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Account that is requesting this Cross Connect.</description>
    <label>Origination Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cross Connects</relationshipLabel>
    <relationshipName>Cross_Connects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Cross_Connect__c/fields/Origination_Port__c.field-meta.xml
<CustomField>
    <fullName>Origination_Port__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Port of the Account that is requesting this Cross Connect.</description>
    <label>Origination Port</label>
    <referenceTo>DC_Port__c</referenceTo>
    <relationshipLabel>Cross Connects</relationshipLabel>
    <relationshipName>Cross_Connects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Cross_Connect__c/fields/Xconnect_date__c.field-meta.xml
<CustomField>
    <fullName>Xconnect_date__c</fullName>
    <description>The date that this Cross Connect was connected.</description>
    <label>Xconnect date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DC_Data_Hall__c/DC_Data_Hall__c.object-meta.xml
<CustomObject>
    <label>Data Hall</label>
    <nameField>
        <label>Data Hall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Halls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Data_Hall__c/fields/DC_Floor__c.field-meta.xml
<CustomField>
    <fullName>DC_Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DC Floor</label>
    <referenceTo>DC_Floor__c</referenceTo>
    <relationshipLabel>Data Halls</relationshipLabel>
    <relationshipName>Data_Halls</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Data_Hall__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Four character short name of the data hall used to support naming convention.</description>
    <label>Short Name</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DC_Floor__c/DC_Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Floor__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Floor__c/fields/Floor_number__c.field-meta.xml
<CustomField>
    <fullName>Floor_number__c</fullName>
    <description>The numerical level of the floor - decimal reserved for Mezzanine spaces.</description>
    <label>Floor_Number</label>
    <precision>3</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Floor__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Two character short name of the floor used to support naming convention.</description>
    <label>Short Name</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Floor__c/fields/Total_Square_Feet__c.field-meta.xml
<CustomField>
    <fullName>Total_Square_Feet__c</fullName>
    <description>Total square footage of this floor</description>
    <label>Total Square Feet</label>
    <precision>7</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Meet_Me_Room__c/DC_Meet_Me_Room__c.object-meta.xml
<CustomObject>
    <label>Meet Me Room</label>
    <nameField>
        <label>Meet Me Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meet Me Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Meet_Me_Room__c/fields/Data_Hall__c.field-meta.xml
<CustomField>
    <fullName>Data_Hall__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Data Hall</label>
    <referenceTo>DC_Data_Hall__c</referenceTo>
    <relationshipLabel>Meet Me Rooms</relationshipLabel>
    <relationshipName>Meet_Me_Rooms</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Meet_Me_Room__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Two character short name of the MMR used to support naming convention.</description>
    <label>Short Name</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Panel__c/DC_Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <label>Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Panel__c/fields/Height_RU__c.field-meta.xml
<CustomField>
    <fullName>Height_RU__c</fullName>
    <description>Height of this Panel in RU</description>
    <label>Height (RU)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Panel__c/fields/Mod_Model__c.field-meta.xml
<CustomField>
    <fullName>Mod_Model__c</fullName>
    <description>Do you manage your Meet Me Room Panels using the Mod model?</description>
    <label>Mod Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DC_Panel__c/fields/MRI_Suite_ID__c.field-meta.xml
<CustomField>
    <fullName>MRI_Suite_ID__c</fullName>
    <label>MRI Suite ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Panel__c/fields/Number_of_Ports_Tall__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Ports_Tall__c</fullName>
    <description>How many ports are across the entire panel (up and down)</description>
    <label>Number of Ports Tall</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Panel__c/fields/Number_of_Ports_Wide__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Ports_Wide__c</fullName>
    <description>How many ports are across the entire panel (left and right)</description>
    <label>Number of Ports Wide</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Panel__c/fields/Rack__c.field-meta.xml
<CustomField>
    <fullName>Rack__c</fullName>
    <label>Rack</label>
    <referenceTo>DC_Rack__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DC_Panel__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Two character short name of the Panel used to support naming convention.</description>
    <label>Short Name</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Port__c/DC_Port__c.object-meta.xml
<CustomObject>
    <label>Port</label>
    <nameField>
        <label>Port Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Port__c/fields/Panel__c.field-meta.xml
<CustomField>
    <fullName>Panel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Panel this Port is on.</description>
    <label>Panel</label>
    <referenceTo>DC_Panel__c</referenceTo>
    <relationshipLabel>Ports</relationshipLabel>
    <relationshipName>Ports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Port__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Ten character short name of the Port used to support naming convention. Dependent on Mod during automatic creation.</description>
    <label>Short Name</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Rack__c/DC_Rack__c.object-meta.xml
<CustomObject>
    <label>Rack</label>
    <nameField>
        <label>Rack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Rack__c/fields/Meet_Me_Room__c.field-meta.xml
<CustomField>
    <fullName>Meet_Me_Room__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Meet Me Room</label>
    <referenceTo>DC_Meet_Me_Room__c</referenceTo>
    <relationshipLabel>Racks</relationshipLabel>
    <relationshipName>Racks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Rack__c/fields/MRI_Suite_ID__c.field-meta.xml
<CustomField>
    <fullName>MRI_Suite_ID__c</fullName>
    <label>MRI Suite ID</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DC_Rack__c/fields/Number_of_Rack_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Rack_Units__c</fullName>
    <description>Height of this rack in Rack Units</description>
    <label>Number of Rack Units</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DC_Rack__c/fields/Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Short_Name__c</fullName>
    <description>Two character short name of the Rack used to support naming convention.</description>
    <label>Short Name</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DX_viewCrossConnectsInformation_ctrTest.cls
@isTest
public class DX_viewCrossConnectsInformation_ctrTest {
@testSetup
    static void setup() {
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'testcontact@example.com',
            AccountId = testAccount.Id
        );
        insert testContact;
        
        // Create a test user
        User testUser = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Customer Community Login User'].Id,
            FirstName = 'Test',
            LastName = 'User',
            Email = 'testuser@example.com',
            Username = 'testuser@example.com',
            Alias = 'tuser',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ContactId = testContact.Id
        );
        insert testUser;
        
        Building__c objBuilding = new Building__c();
        objBuilding.Name = 'test Building';
        insert objBuilding;
        
        DC_Floor__c objDCFloor = new DC_Floor__c();
        objDCFloor.Name = 'test DC Floor';
        objDCFloor.Short_Name__c = 'te';
        objDCFloor.Building__c = objBuilding.Id;
        objDCFloor.Floor_number__c = 2;
        objDCFloor.Total_Square_Feet__c = 2;
        insert objDCFloor;
        
		DC_Data_Hall__c objDataHall = new DC_Data_Hall__c ();
        objDataHall.Name = 'test DataHall';
        objDataHall.DC_Floor__c = objDCFloor.Id;
        objDataHall.Short_Name__c = 'test';
        insert objDataHall;
        
        DC_Meet_Me_Room__c objMeetMeRoom = new DC_Meet_Me_Room__c();
        objMeetMeRoom.Name = 'test Meet Me Room';
        objMeetMeRoom.Data_Hall__c = objDataHall.Id;
        objMeetMeRoom.Short_Name__c = 'te';
        insert objMeetMeRoom;
        
        DC_Rack__c objRack = new DC_Rack__c();
        objRack.name= 'test Rack';
        objRack.MRI_Suite_ID__c = 'IdSui';
        objRack.Meet_Me_Room__c = objMeetMeRoom.Id;
		objRack.Number_of_Rack_Units__c = 2;
        objRack.Short_Name__c = 'te';
        insert objRack;
        
        DC_Panel__c objPanel = new DC_Panel__c (); 
        objPanel.Name = 'test Panel';
        objPanel.Rack__c = objRack.Id;
		objPanel.Mod_Model__c = 'Yes'; 
		objPanel.Height_RU__c = 2;
        objPanel.MRI_Suite_ID__c = 'text';
		objPanel.Number_of_Ports_Tall__c = 2;
		objPanel.Number_of_Ports_Wide__c = 2;
        objPanel.Short_Name__c = 'Te';
        insert objPanel;
        
        DC_Port__c  objDCPort  = new DC_Port__c();
        objDCPort.Name = 'test DestinationPort';
        objDCPort.Panel__c = objPanel.Id;
        objDCPort.Short_Name__c = 'te';
        insert objDCPort;
        
        DC_Cross_Connect__c crossConnect1 = new DC_Cross_Connect__c();
        crossConnect1.Destination_Account__c = testContact.AccountId;
        crossConnect1.Origination_Account__c = testContact.AccountId;
        crossConnect1.Xconnect_date__c = Date.today();
        crossConnect1.Destination_Port__c = objDCPort.Id;
        crossConnect1.Origination_Port__c = objDCPort.Id;
        insert crossConnect1;
        
        DC_Cross_Connect__c crossConnect2 = new DC_Cross_Connect__c();
        crossConnect2.Destination_Account__c = testContact.AccountId;
		crossConnect2.Origination_Account__c = testContact.AccountId;
        crossConnect2.Xconnect_date__c = Date.today();
		crossConnect2.Destination_Port__c = objDCPort.Id;
        crossConnect2.Origination_Port__c = objDCPort.Id;
        insert crossConnect2;
    }
    
    @isTest
    static void testGetCrossConnets() {
        User testUser = [SELECT Id, ContactId FROM User WHERE Username = 'testuser@example.com'];
        System.runAs(testUser) {
            Test.startTest();
            List<DC_Cross_Connect__c> resultCrossConnects = DX_viewCrossConnectsInformation_ctr.getCrossConnets();
            System.assertequals(!resultCrossConnects.isEmpty(),false);
            Test.stopTest();
        }
    }
}