force-app/main/default/objects/DC_Data_Hall__c/DC_Data_Hall__c.object-meta.xml
<CustomObject>
    <label>Data Hall</label>
    <nameField>
        <label>Data Hall Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Halls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Data_Hall__c/fields/DC_Floor__c.field-meta.xml
<CustomField>
    <fullName>DC_Floor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DC Floor</label>
    <referenceTo>DC_Floor__c</referenceTo>
    <relationshipLabel>Data Halls</relationshipLabel>
    <relationshipName>Data_Halls</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DC_Floor__c/DC_Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Floor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Meet_Me_Room__c/DC_Meet_Me_Room__c.object-meta.xml
<CustomObject>
    <label>Meet Me Room</label>
    <nameField>
        <label>Meet Me Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meet Me Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DC_Rack__c/DC_Rack__c.object-meta.xml
<CustomObject>
    <label>Rack</label>
    <nameField>
        <label>Rack Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DX_PanelSelectorRacks_ctr.cls
/**
 * @Description       : 
 * @Author            : cristianivan.ruiz@salesforce.com
 * @Code Coverage     : 
 * @last modified on  : 01-13-2025
 * @last modified by  : cristianivan.ruiz@salesforce.com
**/
public with sharing class DX_PanelSelectorRacks_ctr {
    
    /**
    * @description method to get wrapper structure for floors information
    * @author cristianivan.ruiz@salesforce.com | 12-11-2024 
    * @param buildingId 
    * @return List<DX_DCIM_DataAccess.wrapperResult> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<DX_DCIM_DataAccess.wrapperResult> getFloors(String buildingId) {
        List<DX_DCIM_DataAccess.wrapperResult> lstwrapperResult = new List<DX_DCIM_DataAccess.wrapperResult>();
        List<DC_Floor__c> lstFloors = DX_DCIM_DataAccess.getFloors(buildingId);
        if(!lstFloors.isEmpty()){
            for(DC_Floor__c item : lstFloors){
                DX_DCIM_DataAccess.wrapperResult objwrapperResult = DX_DCIM_DataAccess.objWrapperResult(item.Id, item.Name);
                lstwrapperResult.add(objwrapperResult);
            }
        }
        return lstwrapperResult;
    }

    /**
    * @description method to get wrapper structure for data halls information
    * @author cristianivan.ruiz@salesforce.com | 12-11-2024 
    * @param floorId 
    * @return List<DX_DCIM_DataAccess.wrapperResult> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<DX_DCIM_DataAccess.wrapperResult> getDataHalls(String floorId) {
        List<DX_DCIM_DataAccess.wrapperResult> lstwrapperResult = new List<DX_DCIM_DataAccess.wrapperResult>();
        List<DC_Data_Hall__c> lstDataHalls = DX_DCIM_DataAccess.getDataHalls(floorId);
        if(!lstDataHalls.isEmpty()){
            for(DC_Data_Hall__c item : lstDataHalls){
                DX_DCIM_DataAccess.wrapperResult objwrapperResult = DX_DCIM_DataAccess.objWrapperResult(item.Id, item.Name);
                lstwrapperResult.add(objwrapperResult);
            }
        }
        return lstwrapperResult;
    }
    /**
    * @description method to get wrapper structure for meet me rooms information
    * @author cristianivan.ruiz@salesforce.com | 12-11-2024 
    * @param dataHallId 
    * @return List<DX_DCIM_DataAccess.wrapperResult> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<DX_DCIM_DataAccess.wrapperResult> getMeetMeRooms(String dataHallId) {
        List<DX_DCIM_DataAccess.wrapperResult> lstwrapperResult = new List<DX_DCIM_DataAccess.wrapperResult>();
        List<DC_Meet_Me_Room__c> lstMeetMeRooms = DX_DCIM_DataAccess.getMeetMeRooms(dataHallId);
        if(!lstMeetMeRooms.isEmpty()){
            for(DC_Meet_Me_Room__c item : lstMeetMeRooms){
                DX_DCIM_DataAccess.wrapperResult objwrapperResult = DX_DCIM_DataAccess.objWrapperResult(item.Id, item.Name);
                lstwrapperResult.add(objwrapperResult);
            }
        }
        return lstwrapperResult;
    }

    /**
    * @description method to get wrapper structure for racks information
    * @author cristianivan.ruiz@salesforce.com | 12-11-2024 
    * @param meetMeRoomId 
    * @return List<DX_DCIM_DataAccess.wrapperResult> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<DX_DCIM_DataAccess.wrapperResult> getRacks(String meetMeRoomId) {
        List<DX_DCIM_DataAccess.wrapperResult> lstwrapperResult = new List<DX_DCIM_DataAccess.wrapperResult>();
        List<DC_Rack__c> lstRacks = DX_DCIM_DataAccess.getRacks(meetMeRoomId);
        if(!lstRacks.isEmpty()){
            for(DC_Rack__c item : lstRacks){
                DX_DCIM_DataAccess.wrapperResult objwrapperResult = DX_DCIM_DataAccess.objWrapperResult(item.Id, item.Name);
                lstwrapperResult.add(objwrapperResult);
            }
        }
        return lstwrapperResult;
    }
    
}